# Main build and github release
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# Homebrew
brews:
  -
    github:
      owner: sampointer
      name: homebrew-dy

    commit_author:
      name: goreleaserbot
      email: sam@outsidethe.net

    folder: Formula
    homepage: "https://github.com/sampointer/dy"
    description: "Construct YAML from a directory tree"
    install : |
      bin.install "dy"

# Packages
nfpms:
  -
    formats:
      - deb
      - rpm
    vendor: "Sam Pointer"
    homepage: "https://github.com/sampointer/dy"
    maintainer: "Sam Pointer <sam@outsidethe.net>"
    description: "Construct YAML from a directory tree"
