# .circleci/config.yml
version: 2.1
workflows:
  main:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - build:
          filters:
            branches:
              only: 
                - master
jobs:
  release:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
  build:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run: go test ./...
      - run: go build -ldflags "-X main.version=$CIRCLE_SHA1"
      - store_artifacts:
          path: kapo
          destination: kapo
